CHANGES.txt
README.md
docs/cli.md
morecantile/errors.py
morecantile/models.py
morecantile/scripts/__init__.py
morecantile/scripts/cli.py
morecantile/utils.py
setup.py
tests/test_cli.py
tests/test_morecantile.py

```
$ morecantile --help
Usage: morecantile [OPTIONS] COMMAND [ARGS]...
Command line interface for the Morecantile Python package.
Options:
-v, --verbose  Increase verbosity.
-q, --quiet    Decrease verbosity.
--version      Show the version and exit.
--help         Show this message and exit.
Commands:
custom          Create Custom TileMatrixSet
shapes          Print the shapes of tiles as GeoJSON.
tiles           Print tiles that overlap or contain a lng/lat point,
bounding box, or GeoJSON objects.
tms             Print TileMatrixSet JSON document.
tms-to-geojson  Print TileMatrixSet MatrixSet as GeoJSON.
```
```
$ morecantile tms --identifier EuropeanETRS89_LAEAQuad | morecantile tms-to-grid --level 5 --collect
$ morecantile shapes "[0, 0, 1]" --identifier EuropeanETRS89_LAEAQuad …
```

CLI and Update

---

morecantile/__init__.py
morecantile/defaults.py
morecantile/scripts/cli.py
setup.cfg

This PR does: 
- remove pkg_resources which slows down module import (~0.3 s) 
- add setup.cfg for bumpversion config (dev)
- add `TILEMATRIXSET_DIRECTORY` environement variable to load user TMS.

Remove pkg_resources and add `TILEMATRIXSET_DIRECTORY` env options

---

.pre-commit-config.yaml
CHANGES.md
CONTRIBUTING.md
morecantile/commons.py
requirements.txt
setup.cfg
setup.py
tox.ini

I was trying to install morecantile to a new venv and spotted that it was missing mercantile package. 
```
$ mkvirtualenv -p python3.9.1 mor   
$ pip install morecantile  
$ morecantile --help                                                                                                                                                                                   127 ↵
Traceback (most recent call last):
File "/Users/pratikyadav/.virtualenvs/mor/bin/morecantile", line 5, in <module>
from morecantile.scripts.cli import cli
File "/Users/pratikyadav/.virtualenvs/mor/lib/python3.9/site-packages/morecantile/scripts/cli.py", line 7, in <module>
from mercantile.scripts import configure_logging, coords, iter_lines, normalize_input
ModuleNotFoundError: No module named 'mercantile'
```

Add mercantile to required installation package   

---

.github/workflows/ci.yml
.github/workflows/gdalversion.yml
CHANGES.md
morecantile/scripts/cli.py
setup.py

closes #50 
closes #49 
we were relying on mercantile for the CLI. the methods used from mercantile were `scripts` method and subject to change in mercantile code base. I think it's safer to bring the function over to avoid breaking changes 
I'm sorry @pratikyadav

remove mercantile from the dependencies

---

CHANGES.md
morecantile/errors.py
morecantile/models.py
tests/conftest.py
tests/test_morecantile.py

radd PointOutsideTMS warning when user do operation outside TMS bounds and fix GDAL related test failures

---

README.md
docs/cli.md
docs/usage.md
morecantile/data/NZTM2000Quad.json
tests/test_models.py
tests/test_morecantile.py

This imports the new NZTM2000Quad tile matrix set from LINZ.

add NZTM2000Quad tile matrix set

---

CHANGES.md
morecantile/__init__.py
morecantile/models.py
setup.cfg
setup.py

ref https://github.com/developmentseed/morecantile/issues/64#issuecomment-921648142
as mentioned in ☝️ Importing rasterio if not needed will slow down the startup. 
```python
%time import morecantile
CPU times: user 258 ms, sys: 35.9 ms, total: 294 ms
Wall time: 360 ms
tms = morecantile.tms.get("WebMercatorQuad")
%time tms.rasterio_crs
CPU times: user 3.11 ms, sys: 479 µs, total: 3.59 ms
Wall time: 3.59 ms
```
```python
%time import morecantile
CPU times: user 102 ms, sys: 12.5 ms, total: 114 ms
Wall time: 114 ms
tms = morecantile.tms.get("WebMercatorQuad")
%time tms.rasterio_crs
CPU times: user 158 ms, sys: 33.6 ms, total: 192 ms
Wall time: 258 ms
%time tms.rasterio_crs
CPU times: user 108 µs, sys: 16 µs, total: 124 µs
Wall time: 125 µs
```
in ☝️ we can see that importing rasterio within …

Import rasterio within the `rasterio_crs` property to speedup startup

---

CHANGES.md
morecantile/models.py
tests/test_models.py

Following up on #67, I tested the changes merged in #68 and found them to _almost_ work, except that the private `_geographic_crs` attr wasn't properly initialized (apparently that has to happen manually in `__init__`). So I fixed that, and added two tests:
1. Create a Mars equivalent to the global web mercator TMS
2. Create a localized TMS centered around the Perseverance landing site
Thanks for your quick action on these suggestions. This is helpful for planetary scientists!

Planetary projection fixes

---

morecantile/models.py
tests/test_models.py

The previous logic resulted in an error
(`OverflowError: cannot convert float infinity to integer`) when
attempting to compute the resolution for a zoom that wasn't defined on
the TMS.

Allow `zoom_for_res` to work for a TMS with a `minzoom` > 0

---

CHANGES.md
morecantile/errors.py
morecantile/models.py
tests/test_morecantile.py

closes https://github.com/developmentseed/morecantile/issues/48
add `parent`, `children`, `neighbors`, `extrema`, `is_valid` methods
There are some difference with how we get the parent/children in comparison to mercantile method because we can't really on only the 1 <-> 4 schema of WebMercator. The general idea is to get the bounds from the tile and then find tile(s) for the bounds at the given zoom level. Tests give the same result as for mercantile 🤷‍♂️

Add missing methods

---

morecantile/models.py
tests/test_models.py

Otherwise a zoom could be chosen that's not in the TileMatrixSet.
This change ensures that a zoom returned by `zoom_for_res` is within the range provided by the `min_z` & `max_z` arguments (or the `TileMatrixSet`'s `minzoom` & `maxzoom`).
Without this change an exception is raised when the nearest zoom to the `res` argument is less than the TMS `minzoom` (when using the default `zoom_level_strategy` of `"auto"`).
I added a test case demonstrating the bug, and then clipped the `zoom_level` to the provided min/max z.
Updated the unit test for `zoom_for_res`. 
An example WMTS with a TileMatrixSet that has a minimum zoom > 0: https://tiles.arcgis.com/tiles/hGdibHYSPO59RG1h/arcgis/rest/services/orthos2021/MapServer/WMTS/1.0.0/WMTSCapabilities.xml
N/A

Clip the adjusted zoom to the provided min/max z in `zoom_for_res`

---

CHANGES.md
morecantile/utils.py
tests/test_utils.py

Updated the meters_per_unit utility function to grab the semi major axis length directly from the CRS ellipsoid. This will help with making TMS specs for other planets more correct. I should look to update the mars related tests to ensure things are working...

allow for non-earth scaleDenominators

---

CHANGES.md
morecantile/models.py
tests/test_models.py

grabs the authority, version and code from the CRS directly to encode the URIs. Related to #92 but can be merged separately. I'm not aware of any issues this would cause but I am open to hearing about them

adds ability to export non-EPSG CRSs URIs

---

CHANGES.md
morecantile/models.py

add `geographic_crs` property in the TileMatrixSet model to return the private `_geographic_crs` attribute

---

CHANGES.md
README.md
docs/src/tms-v2.md
docs/src/usage.md
morecantile/defaults.py
morecantile/models.py
tests/test_morecantile.py

This PR update the model to better match the TMS2.0 specification JSON model found in https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/schemas/tms/2.0/json/tileMatrix.json and https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/schemas/tms/2.0/json/tileMatrixSet.json
- remove `type` 
- add `cellSize` as required field in TileMatrix
- update `tileWidth/tileHeight`  and `matrixWidth/matrixHeight` requirements
- make tile matrix set `id` an **Optional** parameter **BREAKING**
- fix `cornerOfOrigin` type
only `crs` and `tileMatrices` are required in the TileMatrixSet specification (https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/schemas/tms/2.0/json/tileMatrixSet.json#L6) but we use it in the TMS Datastore in …

update model to match TMS2.0 and add descriptions

---

CHANGES.md
morecantile/models.py
tests/test_cli.py
tests/test_models.py
tests/test_morecantile.py

This PR does:
- replace `CRSType` model to better match the TMS spec
- keep CRSType as URI/WKT instead of parsing it to pyproj.CRS
- add `TileMatrixSet._crs` to host the pyproj.CRS version of the TMS crs
IMO While this change the API slightly I don't think this should result a Major version.

Update CRS model and add _crs private attribute

---

CHANGES.md
morecantile/models.py
tests/test_models.py

This PR adds `to_epsg` and `to_wkt` methods to CRSType for compatibility with `4.0`
ref https://github.com/developmentseed/morecantile/pull/123#issuecomment-1580458607
cc @roelarents

proxy to_epsg and to_wkt methods to CRSType

---

CHANGES.md
morecantile/models.py
tests/test_models.py
tests/test_morecantile.py

This PR does:
- remove the useless `_crs` private attribute (because it's already stored in `CRSType._pyproj_crs`)
- add more `to_*` methods to CRSType
I'm only changing a `private` attribute so I'm again not making a Major release for this change 🙈 
@roelarents I'll wait for your 👍 👎 🙏

remove TileMatrixSet _crs private attribute to rely on CRSType _pyproj_crs property

---

morecantile/models.py
tests/test_models.py

This PR fixes couples bugs with the CRS and TileMatrixSet models 
- rename `CRSType` -> `CRS` (and internally use `pyproj.CRS` for pyproj's CRS object)
- enable passing `{"uri": ...}` or `{"wkt": ...}` to define the CRS (per specification) 
- use pyproj.CRS's URI representation with `TileMatrixSet`'s `repr`
- remove `pointOfOrigin` default value (it's required)
- add `"topLeft"` default for `cornerOfOrigin`

better CRS parsing and fix TileMatrixSet model

---

morecantile/models.py
tests/test_models.py

I have a use case where I'd like to define a custom TileMatrixSet that uses a nonary-tree instead of quad-tree (i.e. divide by `3` at each zoom level instead of `2`.)
By default, `TileMatrixSet.custom` uses a hardcoded value of `2` for a quad-tree. This PR adds a `decimation` argument to allow for other divisions when generating a `TileMatrix` at each zoom level. The default value for `decimation` is set to `2` so existing tools are unaffected. This PR also includes tests.

Custom TMS with decimation

---

morecantile/models.py
morecantile/utils.py
tests/test_morecantile.py
tests/test_utils.py

👋
I ran into a strange case when my bbox for of a custom tms crossed the 180th meridian. Happy to add a test, but I now at least see expected results. Here is my example:
```python
import pyproj
import geopandas as gpd
from pyproj import CRS
from morecantile import TileMatrixSet
from shapely.geometry import box
def get_utm_tiles(bbox) -> gpd.GeoDataFrame:
geo = gpd.GeoDataFrame(geometry=[bbox], crs=4326)
utm = geo.estimate_utm_crs()
print(utm)
rs_extent = utm.area_of_use.bounds
tms = TileMatrixSet.custom(crs=utm, extent_crs=CRS.from_epsg(4326), extent=list(rs_extent))
tiles = list(tms.tiles(*geo.total_bounds, zooms=4))
transform = pyproj.Transformer.from_crs(utm, 4326, always_xy=True)
geos = [box(*transform.transform_bounds(*list(tms.xy_bounds(t)), densify_pts=21)) for t in tiles]
return …
```

fix: handle 180th meridian case for `tms.tiles()`

---

morecantile/scripts/cli.py

This PR adds the --tms optional flag to the shapes and tiles CLI commands as is done in [supermorecado](https://github.com/developmentseed/supermorecado/blob/main/supermorecado/scripts/cli.py) to make it easier to work with TMS json files
note! untested presently but presumably it should work... can add tests and such if needed

adds --tms optional argument to the shapes and tiles cli tools

---

.github/workflows/ci.yml
CHANGES.md
morecantile/models.py
pyproject.toml
tests/test_models.py

Likely a lot more could be done here to error catch but this could be reasonably robust as is
This PR just ensures the private geographic_crs parameter will be a Pyproj CRS object (some TMS specs I am using define this with a URN that wasn't getting parsed at the right moment.

update to ensure self._geographic_crs will be a pyproj CRS object. 

---

morecantile/models.py
tests/test_morecantile.py

I discovered another corner case I didn't test for. This PR adds another tests case in order to check we get the expected number of tiles for the case when the west bounds and west tms_bbox crosses the antimeridian, but also for the corresponding east component. 
This prevents a very very large number of tiles being returned for both cases.

fix: handle utm west and east antimeridian

---

.gitignore
morecantile/models.py
tests/test_models.py

Adds two tests that are currently failing to correctly return the expected xy_bbox or bbox for the two CRSs considered. 
not sure why but somehow using IAU CRSs that are inverted (latitude longitude order) doesn't seem to work with the latest #158. Maybe this `_pyproj_crs.geodetic_crs` switching around the axes?

added two tests for mars crs's

---

.github/workflows/ci.yml
.pre-commit-config.yaml
CHANGES.md
morecantile/defaults.py
morecantile/models.py
morecantile/utils.py
pyproject.toml
tests/test_morecantile.py

update python version support and update pyproj version requirement

---

CHANGES.md
morecantile/models.py
pyproject.toml
tests/test_morecantile.py

closes https://github.com/developmentseed/morecantile/issues/176
I'm not yet 💯 convinced about this tbh 
if we would add a `strict=True/False` this will also conflict with variableMatrixWidths TMS because we could have `strict=False` but still raise False for is_valid when Z > maxzoom because we cannot construct Matrix for those. 
I think it's better just to raise `False` to respect the `TMS` definition.

check maxzoom in is_valid

---

CHANGES.md
morecantile/models.py
morecantile/utils.py

same goal as https://github.com/developmentseed/morecantile/pull/167
This PR adds a `geographic_crs` option to both `TileMatrixSet.tile()` and `TileMatrixSet.tiles()` methods which allows user to use either the default Geographic CRS from the TMS's CRS definition or WGS84.
Note: a follow up PR will deprecate Geographic methods (`.bbox`, `.bounds()`, `.lr()`, `.ul()` and `.xy()`) because those methods add much more complexity and TMS shouldn't have to deal with how to transform from/to geographic CRS.

add geographic_crs option in tile and tiles methods

---

CHANGES.md
docs/mkdocs.yml
docs/src/advanced/geographic.md
morecantile/data/NZTM2000Quad.json
morecantile/defaults.py
morecantile/models.py
tests/test_models.py
tests/test_morecantile.py

This PR does:
- add `MORECANTILE_DEFAULT_GEOGRAPHIC_CRS` environment variable to control the default Geographic CRS
- add `TileMatrixSet.set_geographic_crs(crs: pyproj.CRS)` method to overwrite the geographic CRS
Instead of removing the Geographic methods as proposed in #182, this PR adds way to set default geographic CRS for the whole environment or for each TMS object (`set_geographic_crs` method).

refactor geographic crs attribute
