- morecantile/models.py
- tests/test_models.py
- tests/test_morecantile.py
> Custom tms

- .pre-commit-config.yaml
- README.md
- morecantile/__init__.py
- morecantile/models.py
- setup.py
- tests/test_models.py
- tests/test_morecantile.py
- tox.ini
> update pre-commit and add mypy and iSort

- CHANGES.txt
- README.md
- morecantile/__init__.py
- morecantile/commons.py
- morecantile/defaults.py
- morecantile/errors.py
- morecantile/models.py
- morecantile/utils.py
- tests/test_models.py
- tests/test_morecantile.py
> [WIP] add default_TileMatrixSet holder for pre-loaded TMS

- README.md
- morecantile/models.py
- tests/test_models.py
> iter and sort

- CHANGES.txt
- morecantile/models.py
- setup.py
- tests/test_models.py
- tests/test_morecantile.py
> extend TMS beyond Document max zoom level

- CHANGES.md
- morecantile/models.py
- tests/test_models.py
> add zoom_for_res function

- CHANGES.md
- docs/usage.md
- morecantile/__init__.py
- morecantile/commons.py
- morecantile/models.py
- morecantile/utils.py
- setup.py
- tests/test_morecantile.py
> switch to rasterio BoundingBox namedtuple

- CHANGES.md
- morecantile/defaults.py
- tests/test_morecantile.py
> improve defaults TMS list immutability

- CHANGES.md
- morecantile/data/NZTM2000.json
- morecantile/data/NZTM2000Quad.json
> add valid URI for NZTM tile matrix sets

- CHANGES.md
- morecantile/models.py
> allow custom geographic CRS

- .pre-commit-config.yaml
- CHANGES.md
- morecantile/models.py
- morecantile/scripts/cli.py
- tests/test_models.py
> fix _invert_axis method

- CHANGES.md
- README.md
- docs/cli.md
- docs/usage.md
- morecantile/data/WGS1984Quad.json
- tests/test_models.py
- tests/test_morecantile.py
> add WGS1984 TMS

- CHANGES.md
- morecantile/models.py
- morecantile/utils.py
- tests/test_morecantile.py
closes #76 
@sbquinlan can you validate this 🙏
> truncate coordinates to tms bbox

- CHANGES.md
- morecantile/__init__.py
- morecantile/data/README.md
- morecantile/data/WebMercatorQuad.json
- morecantile/data/__init__.py
- morecantile/models.py
- tests/test_mercantile_conform.py
- tests/test_morecantile.py
> Align mer/morcantile

- CHANGES.md
- morecantile/utils.py
- tests/test_utils.py
> add support for foot and Us survey foot defined CRS

- CHANGES.md
- docs/src/cli.md
- morecantile/data/CanadianNAD83_LCC.json
- morecantile/data/EuropeanETRS89_LAEAQuad.json
- morecantile/data/WorldMercatorWGS84Quad.json
- morecantile/scripts/cli.py
- tests/test_cli.py
- tests/test_models.py
fix `CanadianNAD83_LCC`, `WorldMercatorWGS84Quad` and `EuropeanETRS89_LAEAQuad` TMS
> fix some TMS

- CHANGES.md
- docs/src/usage.md
- morecantile/defaults.py
ref https://github.com/AndrewAnnex/planetcantile/pull/2#discussion_r1046879136
```
time python -c'import morecantile'
python -c'import morecantile'  0.19s user 0.03s system 98% cpu 0.222 total
time python -c'import morecantile'
python -c'import morecantile'  0.10s user 0.02s system 96% cpu 0.132 total
```
> only parse TMS when used

- .github/workflows/ci.yml
- CHANGES.md
- README.md
- morecantile/models.py
- morecantile/utils.py
- pyproject.toml
- tests/test_models.py
- tests/test_morecantile.py
> Backport from4.0

- CHANGES.md
- morecantile/models.py
> only use required attribute to create hashkey

- CHANGES.md
- morecantile/models.py
- tests/test_models.py
add `.srs` and forward options to pyproj methods
> add srs and forwards options

- CHANGES.md
- morecantile/models.py
- tests/test_models.py
> OGC says Well Known Text is a PROJJSON object

- CHANGES.md
- morecantile/data/README.md
- morecantile/data/WGS1984Quad.json
> fix WGS1984Quad tms id

- CHANGES.md
- morecantile/models.py
- pyproject.toml
ref https://docs.pydantic.dev/latest/migration/#changes-to-pydanticfield
> update `Field` usage to avoid deprecation in pydantic 3.0

- .github/workflows/ci.yml
- CHANGES.md
- pyproject.toml
> remove python 3.8
